# Generated by Django 3.2.17 on 2025-12-15 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storygraph_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.JSONField(max_length=300)),
                ('pages', models.IntegerField()),
                ('first_published_year', models.IntegerField()),
                ('average_rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Storygraph_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('tag_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tagged_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.storygraph_book')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.storygraph_tag')),
            ],
        ),
    ]
