# Generated by Django 5.2.9 on 2025-12-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_book_id_tagged_book_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagged_book',
            old_name='book',
            new_name='book_id',
        ),
    ]
