# Generated by Django 5.2.9 on 2025-12-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_book_id_tagged_book_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygraph_book',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
