# Generated by Django 5.2.9 on 2026-01-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_synonym_synonym_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastFM_Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entity_Tag_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.synonym')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.lastfm_entity')),
            ],
        ),
    ]
