# Generated by Django 5.2.9 on 2026-02-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_lastfm_entity_entity_tag_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygraph_book',
            name='cover_source',
            field=models.URLField(default=''),
        ),
    ]
