# Generated by Django 5.2.9 on 2026-03-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_storygraph_book_cover_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storygraph_book',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='storygraph_book',
            name='isbn_uid',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='storygraph_book',
            name='number_of_reviews',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='storygraph_book',
            name='pace_percentages',
            field=models.JSONField(default={}, max_length=3000),
        ),
        migrations.AddField(
            model_name='storygraph_book',
            name='storygraph_id',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='storygraph_book',
            name='tag_percentages',
            field=models.JSONField(default={}, max_length=3000),
        ),
        migrations.AddField(
            model_name='storygraph_book',
            name='tag_weights',
            field=models.JSONField(default={}, max_length=3000),
        ),
        migrations.AddField(
            model_name='tagged_book',
            name='weight',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='storygraph_book',
            name='authors',
            field=models.JSONField(max_length=500),
        ),
    ]
