# Generated by Django 5.2.9 on 2026-03-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_remove_storygraph_book_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storygraph_book',
            name='pace_percentages',
            field=models.JSONField(default=dict, max_length=3000),
        ),
        migrations.AlterField(
            model_name='storygraph_book',
            name='tag_percentages',
            field=models.JSONField(default=dict, max_length=3000),
        ),
        migrations.AlterField(
            model_name='storygraph_book',
            name='tag_weights',
            field=models.JSONField(default=dict, max_length=3000),
        ),
    ]
