# Generated by Django 5.2.9 on 2026-03-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_storygraph_book_pace_percentages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonym_relation',
            name='affinity',
            field=models.CharField(default='', max_length=50),
        ),
    ]
