# Generated by Django 5.2.9 on 2026-03-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_synonym_relation_affinity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastfm_entity',
            old_name='type',
            new_name='artist',
        ),
        migrations.AddField(
            model_name='entity_tag_relation',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lastfm_entity',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
    ]
