# Generated by Django 5.2.9 on 2026-03-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_rename_type_lastfm_entity_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify_Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('tag', models.CharField(default='', max_length=100)),
                ('spotify_json', models.JSONField(default=dict, max_length=15000)),
            ],
        ),
        migrations.CreateModel(
            name='Spotify_Tag_Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=100)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.synonym')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.spotify_track')),
            ],
        ),
    ]
